### Listar de Eventos
GET https://localhost:7195/api/evento/listar

### Buscar Eventos
GET https://localhost:7195/api/evento/buscar/Evento1

### Cadastrar evento
POST https://localhost:7195/api/evento/cadastrar
Content-Type: application/json

{
    "Nome" : "EventX",
    "Descricao" : "Descricao do evento",
    "DataEvento" : "2023-11-04T22:02:25.551423",
    "ONGId" : 2
}

### Atualizar evento
PUT https://localhost:7195/api/evento/atualizar/2
Content-Type: application/json

{
    "Nome" : "evento2",
    "Descricao" : "Descricao do evento",
    "DataEvento" : "2023-11-04T22:02:25.551423",
    "ONGId" : 2

}

### Delete ong
DELETE https://localhost:7195/api/evento/delete/1
Content-Type: application/json