### Listar de ONGs
GET https://localhost:7195/api/ong/listar

### Buscar ONGs
GET https://localhost:7195/api/ong/buscar/ONG1

### Cadastrar ong
POST https://localhost:7195/api/ong/cadastrar
Content-Type: application/json

{
    "nome" : "ONG2",
    "missao": "null",
    "historico": "null",
    "informacoesContato": "null"
}