### Listar de ONGs
GET https://localhost:7195/api/ong/listar

### Buscar ONGs
GET https://localhost:7195/api/ong/buscar/ONG1

### Cadastrar ong
POST https://localhost:7195/api/ong/cadastrar
Content-Type: application/json

{
    "nome" : "ONG22",
    "missao": "null",
    "historico": "null",
    "informacoesContato": "null"
}

### Atualizar ONG
PUT https://localhost:7195/api/ong/atualizar/7
Content-Type: application/json

{
"nome" : "ONG1",
"novaMissao": "Nova Missão",
"novoHistorico": "Novo Histórico",
"novasInformacoesContato": "Novas Informações de Contato"
}

### Delete ong
DELETE https://localhost:7195/api/ong/delete/1
Content-Type: application/json