### Listar de ONGs
GET https://localhost:7195/api/ong/listar

### Buscar ONGs
GET https://localhost:7195/api/ong/buscar/Ong Teste

### Cadastrar ong
POST https://localhost:7195/api/ong/cadastrar
Content-Type: application/json

{
    "nome" : "Ong Teste",
    "missao": "Missao teste",
    "historico": "Historico teste",
    "informacoesContato": "Contato teste"
}

### Atualizar ONG
PUT https://localhost:7195/api/ong/atualizar/3
Content-Type: application/json

{
    "nome" : "Ong Teste atualizado",
    "missao": "Missao teste atualizado",
    "historico": "Historico teste atualizado",
    "informacoesContato": "Contato teste atualizado"
}

### Delete ong
DELETE https://localhost:7195/api/ong/delete/6