### Listar de pessoas
GET https://localhost:7195/api/pessoa/listar

### Buscar pessoas
GET https://localhost:7195/api/pessoa/buscar/NomePessoa

### Cadastrar pessoa
POST https://localhost:7195/api/pessoa/cadastrar
Content-Type: application/json

{
    "nome" : "Sophia", 
    //adicionar
}