### Listar de pessoas
GET https://localhost:7195/api/pessoa/listar

### Buscar pessoas
GET https://localhost:7195/api/pessoa/buscar/NomePessoa

### Cadastrar pessoa
POST https://localhost:7195/api/pessoa/cadastrar
Content-Type: application/json

{
    "Nome" : "Joao das Neves",
    "endereco": "Endereço",
    "numeroTelefone": "(41)789413213",
    "email": "contato@gmail.com"
}