### Listar de produtos
GET https://localhost:7195/api/produto/listar

### Buscar produtos
GET https://localhost:7195/api/produto/buscar/Arroz

### Cadastrar produto
POST https://localhost:7195/api/produto/cadastrar
Content-Type: application/json

{
    "nome" : "Sophia", 
    "quantidade": 22,
    "preco": 150
}