### Listar de Animais
GET https://localhost:7195/api/animal/listar

### Buscar Animais
GET https://localhost:7195/api/animal/buscar/NomeAnimal

### Cadastrar animal
POST https://localhost:7195/api/animal/cadastrar

### Atualizar animal
PUT https://localhost:7195/api/animal/atualizar/1
Content-Type: application/json

{
    "nome": "AnimalTesteAtualizad", 
    "Idade": "12",
    "Especie": "Cachorro",
    "Raca": "Vira-lata",
    "Porte": "Pequeno",
    "Comportamento": "Dócil",
    "Descricao": "Desc",
    "Foto": null,
    "Video": null,
    "ONGId": 1 
}


### AdicionarFotos
POST: api/animal/adicionarFotos/{id}