### Listar de Animais
GET https://localhost:7195/api/animal/listar

### Buscar Animais
GET https://localhost:7195/api/animal/buscar/EventX

### Cadastrar Animal
POST https://localhost:7195/api/animal/cadastrar
Content-Type: application/json

{
    "Nome" : "Cadastro Pet Teste",
    "Idade": "10 anos",
    "Especie": "Especie teste",
    "Raca": "Raca teste",
    "Porte": "Porte teste",
    "Comportamento": "Comportamento teste",
    "Descricao": "Descricao teste",
    "Foto" : "url foto teste",
    "Video" : "video url teste",
    "ONGId" : 1
}

### Atualizar Animal
PUT https://localhost:7195/api/animal/atualizar/1
Content-Type: application/json

{
    "Nome" : "Cadastro Atualizado",
    "Idade": "11 anos",
    "Especie": "Especie teste atualizado",
    "Raca": "Raca teste atualizado",
    "Porte": "Porte teste atualizado",
    "Comportamento": "Comportamento teste atualizado",
    "Descricao": "Descricao teste atualizado",
    "Foto" : "url foto teste atualizado",
    "Video" : "video url teste atualizado",
    "ONGId" : 1
}

### Delete animal
DELETE https://localhost:7195/api/animal/delete/1