### Listar de eventos
GET https://localhost:7195/api/evento/listar

### Buscar eventos
GET https://localhost:7195/api/evento/buscar/NomeEvento

### Atualizar eventos
PUT https://localhost:7195/api/evento/atualizar/1
Content-Type: application/json

{
    "Nome": "Evento Teste Atualizado",
    "Descricao": "Descricao teste",
    "ONGId": 1
}

### Cadastrar evento
POST https://localhost:7195/api/evento/cadastrar