### Listar de Eventos
GET https://localhost:7195/api/evento/listar

### Buscar Eventos
GET https://localhost:7195/api/evento/buscar/Evento1

### Cadastrar evento
POST https://localhost:7195/api/evento/cadastrar
Content-Type: application/json

{
    "Nome" : "Evento teste",
    "Descricao" : "Descricao do evento teste",
    "DataEvento" : "2023-11-04T22:02:25.551423",
    "ONGId" : 1
}

### Atualizar evento
PUT https://localhost:7195/api/evento/atualizar/1

### Delete ong
DELETE https://localhost:7195/api/evento/delete/1