### Listar de eventos
GET https://localhost:7195/api/evento/listar

### Buscar eventos
GET https://localhost:7195/api/evento/buscar/NomeEvento

### Cadastrar evento
POST https://localhost:7195/api/evento/cadastrar
Content-Type: application/json

{
    "Nome": "Evento Test",
    "Descricao": "Evento de doacao teste",
    "ONGId": "1"  
    //adicionar
}