### Listar de ongs
GET https://localhost:7195/api/ong/listar

### Buscar ongs
GET https://localhost:7195/api/ong/buscar/NomeOng

### Atualizar ongs
PUT https://localhost:7195/api/ong/atualizar/1

### Cadastrar ong
POST https://localhost:7195/api/ong/cadastrar
Content-Type: application/json

{
    "Nome": "Ong Teste 2",
    "Missao": "Missao teste",
    "Historico": "Historico teste",
    "InformacoesContato": "Contato teste"
}

### Deletar ONG
DELETE https://localhost:7195/api/ong/delete/2