### Listar de ongs
GET https://localhost:7195/api/ong/listar

### Buscar ongs
GET https://localhost:7195/api/ong/buscar/NomeOng

### Cadastrar ong
POST https://localhost:7195/api/ong/cadastrar
Content-Type: application/json

{
    "Nome": "Ong Teste",
    "Missao": "Missao teste",
    "Historico": "Historico teste",
    "InformacoesContato": "Contato teste"

}