### Listar de Pessoas
GET https://localhost:7195/api/pessoa/listar

### Buscar Pessoas
GET https://localhost:7195/api/pessoa/buscar/Joacir

### Cadastrar Pessoa
POST https://localhost:7195/api/pessoa/cadastrar
Content-Type: application/json

{
    "nome" : "Pessoa teste",
    "endereco": "Rua teste",
    "numeroTelefone": "(41)0000-0000",
    "email": "pessoa@email.com"
    
}

### Atualizar Pessoa 
PUT https://localhost:7195/api/pessoa/atualizar/1

### Delete Pessoa
DELETE https://localhost:7195/api/pessoa/delete/1